import { palette } from '../src/colorspec.ts';

// 1. Define the output path relative to this script
const outputPath = new URL('../src/colors.gen.ts', import.meta.url);

const lines: string[] = [
  '// This file is auto-generated by scripts/prebuild.ts. Do not edit directly.',
  "import { rgb24 } from '@std/fmt/colors';",
  "import { palette } from './colorspec.ts';",
  '',
];

// 2. Safely iterate over the palette keys using for...of
for (const name of Object.keys(palette)) {
  lines.push(`export const ${name} = (s: string): string => rgb24(s, palette.${name});`);
}

try {
  // 3. Write the file to the src/ directory
  await Deno.writeTextFile(outputPath, lines.join('\n') + '\n');
  console.log(`Successfully generated: src/colors.gen.ts`);
} catch (error) {
  console.error('Failed to write generated color file:', error);
  Deno.exit(1);
}
