import { palette } from '../src/colorspec.ts';

const outputPath = new URL('../src/colors.gen.ts', import.meta.url);

const lines: string[] = [
  '// This file is auto-generated by scripts/prebuild.ts. Do not edit directly.',
  "import { rgb24 } from '@std/fmt/colors';",
  "import { palette } from './colorspec.ts';",
  '',
];

for (const name of Object.keys(palette)) {
  lines.push(`export const ${name} = (s: string): string => rgb24(s, palette.${name});`);
}

const newContent = lines.join('\n') + '\n';

try {
  // 1. Read the existing file if it exists
  const existingContent = await Deno.readTextFile(outputPath).catch(() => null);

  // 2. Only write if the content has actually changed
  if (existingContent === newContent) {
    console.log(`src/colors.gen.ts is up to date (no changes).`);
  } else {
    await Deno.writeTextFile(outputPath, newContent);
    console.log(`Successfully generated: src/colors.gen.ts`);
  }
} catch (error) {
  console.error('Failed to process color file generation:', error);
  Deno.exit(1);
}
