(function () {
  window.DENO_DOC_SEARCH_INDEX = {
    'kind': 'search',
    'nodes': [{
      'id': 'namespace_filespec',
      'kind': [{ 'char': 'c', 'kind': 'Class', 'title': 'Class' }],
      'name': 'FileSpec',
      'file': '.',
      'doc': 'Class representing a file system entry when it is known to be a file.',
      'url': '././~/FileSpec.html',
      'deprecated': false,
    }, {
      'id': 'namespace_filespec',
      'kind': [{ 'char': 'm', 'kind': 'Method', 'title': 'Method' }],
      'name': 'FileSpec.prototype.path',
      'file': '.',
      'doc': '',
      'url': '././~/FileSpec.prototype.path.html',
      'deprecated': false,
    }, {
      'id': 'namespace_filespec',
      'kind': [{ 'char': 'm', 'kind': 'Method', 'title': 'Method' }],
      'name': 'FileSpec.fromMeta',
      'file': '.',
      'doc':
        'Creates a new FileSpec from a file URL, typically from import.meta.url. This allows for creating paths relative to the current module.',
      'url': '././~/FileSpec.fromMeta.html',
      'category': 'Factory Methods',
      'deprecated': false,
    }, {
      'id': 'namespace_filespec',
      'kind': [{ 'char': 'm', 'kind': 'Method', 'title': 'Method' }],
      'name': 'FileSpec.cwd',
      'file': '.',
      'doc':
        'Creates a new FileSpec for the current working directory, optionally with additional path segments appended.',
      'url': '././~/FileSpec.cwd.html',
      'category': 'Factory Methods',
      'deprecated': false,
    }, {
      'id': 'namespace_filespec',
      'kind': [{ 'char': 'm', 'kind': 'Method', 'title': 'Method' }],
      'name': 'FileSpec.home',
      'file': '.',
      'doc': "Creates a new FileSpec for the user's home directory, optionally with additional path segments appended.",
      'url': '././~/FileSpec.home.html',
      'category': 'Factory Methods',
      'deprecated': false,
    }, {
      'id': 'namespace_filespec',
      'kind': [{ 'char': 'm', 'kind': 'Method', 'title': 'Method' }],
      'name': 'FileSpec.config',
      'file': '.',
      'doc':
        "Creates a new FileSpec for a file in the user's config directory. Follows XDG Base Directory Specification:Checks XDG_CONFIG_HOME environment variable firstFalls back to ~/.config on macOS and LinuxFalls back to %APPDATA% on Windows (via home directory resolution)",
      'url': '././~/FileSpec.config.html',
      'category': 'Factory Methods',
      'deprecated': false,
    }, {
      'id': 'namespace_filespec',
      'kind': [{ 'char': 'm', 'kind': 'Method', 'title': 'Method' }],
      'name': 'FileSpec.makeTemp',
      'file': '.',
      'doc':
        "Creates a new temporary file in the default directory for temporary files, unless dir is specified.Other options include prefixing and suffixing the directory name with prefix and suffix respectively.This call resolves to the full path to the newly created file.Multiple programs calling this function simultaneously will create different files. It is the caller's responsibility to remove the file when no longer needed.Requires allow-write permission",
      'url': '././~/FileSpec.makeTemp.html',
      'category': 'Factory Methods',
      'deprecated': false,
    }, {
      'id': 'namespace_filespec',
      'kind': [{ 'char': 'm', 'kind': 'Method', 'title': 'Method' }],
      'name': 'FileSpec.fromFileUrl',
      'file': '.',
      'doc': 'Creates a new FileSpec from a file:// URL string.',
      'url': '././~/FileSpec.fromFileUrl.html',
      'category': 'Factory Methods',
      'deprecated': false,
    }, {
      'id': 'namespace_filespec',
      'kind': [{ 'char': 'm', 'kind': 'Method', 'title': 'Method' }],
      'name': 'FileSpec.prototype.basename',
      'file': '.',
      'doc':
        "Returns the file's base file name, minus it's extension. For example, for '/path/to/file.name.html', this method will return 'file.name'. Unlike node:path basename method, this does NOT include the extension.",
      'url': '././~/FileSpec.prototype.basename.html',
      'category': 'Path Properties',
      'deprecated': false,
    }, {
      'id': 'namespace_filespec',
      'kind': [{ 'char': 'm', 'kind': 'Method', 'title': 'Method' }],
      'name': 'FileSpec.prototype.filename',
      'file': '.',
      'doc': '',
      'url': '././~/FileSpec.prototype.filename.html',
      'category': 'Path Properties',
      'deprecated': false,
    }, {
      'id': 'namespace_filespec',
      'kind': [{ 'char': 'm', 'kind': 'Method', 'title': 'Method' }],
      'name': 'FileSpec.prototype.isBasename',
      'file': '.',
      'doc': 'Test for equality with the basename (no extension) of this file.',
      'url': '././~/FileSpec.prototype.isBasename.html',
      'deprecated': false,
    }, {
      'id': 'namespace_filespec',
      'kind': [{ 'char': 'm', 'kind': 'Method', 'title': 'Method' }],
      'name': 'FileSpec.prototype.extname',
      'file': '.',
      'doc':
        "Returns the extension with the dot included. For example, '/path/to/file.name.html' will return '.html'. If the file has no extension, or if the filename starts with a dot and has no other dots (like a .gitignore file), it returns an empty string.",
      'url': '././~/FileSpec.prototype.extname.html',
      'category': 'Path Properties',
      'deprecated': false,
    }, {
      'id': 'namespace_filespec',
      'kind': [{ 'char': 'm', 'kind': 'Method', 'title': 'Method' }],
      'name': 'FileSpec.prototype.ext',
      'file': '.',
      'doc': '',
      'url': '././~/FileSpec.prototype.ext.html',
      'category': 'Path Properties',
      'deprecated': false,
    }, {
      'id': 'namespace_filespec',
      'kind': [{ 'char': 'm', 'kind': 'Method', 'title': 'Method' }],
      'name': 'FileSpec.prototype.parentFolder',
      'file': '.',
      'doc': 'Return the FolderSpec for the folder that contains this file.',
      'url': '././~/FileSpec.prototype.parentFolder.html',
      'category': 'Path Properties',
      'deprecated': false,
    }, {
      'id': 'namespace_filespec',
      'kind': [{ 'char': 'm', 'kind': 'Method', 'title': 'Method' }],
      'name': 'FileSpec.prototype.isExtType',
      'file': '.',
      'doc': 'Looks at the extension of the filename to determine if it is one of the listed types.',
      'url': '././~/FileSpec.prototype.isExtType.html',
      'category': 'Type Checking',
      'deprecated': false,
    }, {
      'id': 'namespace_filespec',
      'kind': [{ 'char': 'm', 'kind': 'Method', 'title': 'Method' }],
      'name': 'FileSpec.prototype.isPdf',
      'file': '.',
      'doc': 'Tests the extension to see if this is a PDF file.',
      'url': '././~/FileSpec.prototype.isPdf.html',
      'category': 'Type Checking',
      'deprecated': false,
    }, {
      'id': 'namespace_filespec',
      'kind': [{ 'char': 'm', 'kind': 'Method', 'title': 'Method' }],
      'name': 'FileSpec.prototype.isXml',
      'file': '.',
      'doc': 'Tests the extension to see if this is an XML file.',
      'url': '././~/FileSpec.prototype.isXml.html',
      'category': 'Type Checking',
      'deprecated': false,
    }, {
      'id': 'namespace_filespec',
      'kind': [{ 'char': 'm', 'kind': 'Method', 'title': 'Method' }],
      'name': 'FileSpec.prototype.isTxt',
      'file': '.',
      'doc': 'Tests the extension to see if this is a text file.',
      'url': '././~/FileSpec.prototype.isTxt.html',
      'category': 'Type Checking',
      'deprecated': false,
    }, {
      'id': 'namespace_filespec',
      'kind': [{ 'char': 'm', 'kind': 'Method', 'title': 'Method' }],
      'name': 'FileSpec.prototype.isJson',
      'file': '.',
      'doc': 'Tests the extension to see if this is a JSON file.',
      'url': '././~/FileSpec.prototype.isJson.html',
      'category': 'Type Checking',
      'deprecated': false,
    }, {
      'id': 'namespace_filespec',
      'kind': [{ 'char': 'm', 'kind': 'Method', 'title': 'Method' }],
      'name': 'FileSpec.prototype.isJsonc',
      'file': '.',
      'doc': 'Tests the extension to see if this is a JSONC file.',
      'url': '././~/FileSpec.prototype.isJsonc.html',
      'category': 'Type Checking',
      'deprecated': false,
    }, {
      'id': 'namespace_filespec',
      'kind': [{ 'char': 'm', 'kind': 'Method', 'title': 'Method' }],
      'name': 'FileSpec.prototype.copy',
      'file': '.',
      'doc': 'Return a copy of this object. Does not copy the file.',
      'url': '././~/FileSpec.prototype.copy.html',
      'deprecated': false,
    }, {
      'id': 'namespace_filespec',
      'kind': [{ 'char': 'm', 'kind': 'Method', 'title': 'Method' }],
      'name': 'FileSpec.prototype.copyParamsTo',
      'file': '.',
      'doc': '',
      'url': '././~/FileSpec.prototype.copyParamsTo.html',
      'deprecated': false,
    }, {
      'id': 'namespace_filespec',
      'kind': [{ 'char': 'm', 'kind': 'Method', 'title': 'Method' }],
      'name': 'FileSpec.prototype.add',
      'file': '.',
      'doc': 'Appends additional path segments to the current file system path.',
      'url': '././~/FileSpec.prototype.add.html',
      'category': 'Path Manipulation',
      'deprecated': false,
    }, {
      'id': 'namespace_filespec',
      'kind': [{ 'char': 'm', 'kind': 'Method', 'title': 'Method' }],
      'name': 'FileSpec.prototype.relativeTo',
      'file': '.',
      'doc':
        'Returns the relative path from this file to a target folder or file.This is useful for creating clean, readable paths for display or for constructing relative imports. The returned path uses forward slashes regardless of platform.',
      'url': '././~/FileSpec.prototype.relativeTo.html',
      'category': 'Path Manipulation',
      'deprecated': false,
    }, {
      'id': 'namespace_filespec',
      'kind': [{ 'char': 'm', 'kind': 'Method', 'title': 'Method' }],
      'name': 'FileSpec.prototype.depth',
      'file': '.',
      'doc':
        'Returns the depth of this file relative to an ancestor folder.Computes how many directory levels deep this file is from the specified ancestor. Returns -1 if the specified folder is not actually an ancestor.',
      'url': '././~/FileSpec.prototype.depth.html',
      'category': 'Path Manipulation\n',
      'deprecated': false,
    }, {
      'id': 'namespace_filespec',
      'kind': [{ 'char': 'm', 'kind': 'Method', 'title': 'Method' }],
      'name': 'FileSpec.prototype.setExt',
      'file': '.',
      'doc': 'Set or change the extension of this file. This must be a file.',
      'url': '././~/FileSpec.prototype.setExt.html',
      'category': 'Path Manipulation',
      'deprecated': false,
    }, {
      'id': 'namespace_filespec',
      'kind': [{ 'char': 'm', 'kind': 'Method', 'title': 'Method' }],
      'name': 'FileSpec.prototype.setBasename',
      'file': '.',
      'doc': 'Set or change the basename of this file. This must be a file.',
      'url': '././~/FileSpec.prototype.setBasename.html',
      'category': 'Path Manipulation',
      'deprecated': false,
    }, {
      'id': 'namespace_filespec',
      'kind': [{ 'char': 'm', 'kind': 'Method', 'title': 'Method' }],
      'name': 'FileSpec.prototype.toFileUrl',
      'file': '.',
      'doc': 'Returns the file:// URL for this file path.',
      'url': '././~/FileSpec.prototype.toFileUrl.html',
      'category': 'Path Manipulation',
      'deprecated': false,
    }, {
      'id': 'namespace_filespec',
      'kind': [{ 'char': 'm', 'kind': 'Method', 'title': 'Method' }],
      'name': 'FileSpec.prototype.size',
      'file': '.',
      'doc': '',
      'url': '././~/FileSpec.prototype.size.html',
      'category': 'File Metadata',
      'deprecated': false,
    }, {
      'id': 'namespace_filespec',
      'kind': [{ 'char': 'm', 'kind': 'Method', 'title': 'Method' }],
      'name': 'FileSpec.prototype.getBytes',
      'file': '.',
      'doc':
        'Asynchronously reads a specified number of bytes from the file and returns them as an FSBytes instance. In order to determine what type of file this is, at least 24 bytes must be read.',
      'url': '././~/FileSpec.prototype.getBytes.html',
      'category': 'File Metadata',
      'deprecated': false,
    }, {
      'id': 'namespace_filespec',
      'kind': [{ 'char': 'm', 'kind': 'Method', 'title': 'Method' }],
      'name': 'FileSpec.prototype.getPdfDate',
      'file': '.',
      'doc': 'For PDF files, gets the Creation Date of this file by reading its metadata using PDFMetadataReader.',
      'url': '././~/FileSpec.prototype.getPdfDate.html',
      'category': 'File Metadata',
      'deprecated': false,
    }, {
      'id': 'namespace_filespec',
      'kind': [{ 'char': 'm', 'kind': 'Method', 'title': 'Method' }],
      'name': 'FileSpec.prototype.open',
      'file': '.',
      'doc': '',
      'url': '././~/FileSpec.prototype.open.html',
      'category': 'File I/O',
      'deprecated': false,
    }, {
      'id': 'namespace_filespec',
      'kind': [{ 'char': 'm', 'kind': 'Method', 'title': 'Method' }],
      'name': 'FileSpec.prototype.close',
      'file': '.',
      'doc': '',
      'url': '././~/FileSpec.prototype.close.html',
      'category': 'File I/O',
      'deprecated': false,
    }, {
      'id': 'namespace_filespec',
      'kind': [{ 'char': 'm', 'kind': 'Method', 'title': 'Method' }],
      'name': 'FileSpec.prototype.readBytes',
      'file': '.',
      'doc': '',
      'url': '././~/FileSpec.prototype.readBytes.html',
      'category': 'File I/O',
      'deprecated': false,
    }, {
      'id': 'namespace_filespec',
      'kind': [{ 'char': 'm', 'kind': 'Method', 'title': 'Method' }],
      'name': 'FileSpec.prototype.readAsBytes',
      'file': '.',
      'doc': 'Reads the entire file as a Uint8Array. Can optionally decode base64-encoded content.',
      'url': '././~/FileSpec.prototype.readAsBytes.html',
      'category': 'Read Operations',
      'deprecated': false,
    }, {
      'id': 'namespace_filespec',
      'kind': [{ 'char': 'm', 'kind': 'Method', 'title': 'Method' }],
      'name': 'FileSpec.prototype.readAsString',
      'file': '.',
      'doc': 'Reads the entire file as a string. Can optionally decode base64-encoded content.',
      'url': '././~/FileSpec.prototype.readAsString.html',
      'category': 'Read Operations',
      'deprecated': false,
    }, {
      'id': 'namespace_filespec',
      'kind': [{ 'char': 'm', 'kind': 'Method', 'title': 'Method' }],
      'name': 'FileSpec.prototype.readAsLines',
      'file': '.',
      'doc': 'Reads the file as a string and splits it into lines.',
      'url': '././~/FileSpec.prototype.readAsLines.html',
      'category': 'Read Operations',
      'deprecated': false,
    }, {
      'id': 'namespace_filespec',
      'kind': [{ 'char': 'm', 'kind': 'Method', 'title': 'Method' }],
      'name': 'FileSpec.prototype.readJson',
      'file': '.',
      'doc':
        'Reads the file as JSON and parses it, optionally stripping comments for JSONC files. Supports both standard JSON and JSON-with-comments (JSONC) formats.',
      'url': '././~/FileSpec.prototype.readJson.html',
      'category': 'Read Operations',
      'deprecated': false,
    }, {
      'id': 'namespace_filespec',
      'kind': [{ 'char': 'm', 'kind': 'Method', 'title': 'Method' }],
      'name': 'FileSpec.prototype.readToml',
      'file': '.',
      'doc':
        'Reads the file as TOML and parses it. The @std/toml dependency is loaded dynamically only when this method is called.',
      'url': '././~/FileSpec.prototype.readToml.html',
      'category': 'Read Operations',
      'deprecated': false,
    }, {
      'id': 'namespace_filespec',
      'kind': [{ 'char': 'm', 'kind': 'Method', 'title': 'Method' }],
      'name': 'FileSpec.prototype.readYaml',
      'file': '.',
      'doc':
        'Reads the file as YAML and parses it. The @std/yaml dependency is loaded dynamically only when this method is called.',
      'url': '././~/FileSpec.prototype.readYaml.html',
      'category': 'Read Operations',
      'deprecated': false,
    }, {
      'id': 'namespace_filespec',
      'kind': [{ 'char': 'm', 'kind': 'Method', 'title': 'Method' }],
      'name': 'FileSpec.prototype.write',
      'file': '.',
      'doc': 'Writes data to the file.',
      'url': '././~/FileSpec.prototype.write.html',
      'category': 'Write Operations',
      'deprecated': false,
    }, {
      'id': 'namespace_filespec',
      'kind': [{ 'char': 'm', 'kind': 'Method', 'title': 'Method' }],
      'name': 'FileSpec.prototype.writeBase64',
      'file': '.',
      'doc': 'Encodes input as base64 and writes to the file.',
      'url': '././~/FileSpec.prototype.writeBase64.html',
      'category': 'Write Operations',
      'deprecated': false,
    }, {
      'id': 'namespace_filespec',
      'kind': [{ 'char': 'm', 'kind': 'Method', 'title': 'Method' }],
      'name': 'FileSpec.prototype.writeJson',
      'file': '.',
      'doc':
        'Writes JSON data to the file with flexible parameter handling.This method supports multiple parameter combinations to provide maximum flexibility:Basic usage: writeJson(data)With safe write: writeJson(data, { safe: true }) // uses renameWithTildeWith formatting: writeJson(data, replacer, space)With deep copy: writeJson(data, deepCopyOpts)Combined options: writeJson(data, replacer, space, { safe: true })And many other combinations...Uses a high-durability write strategy: opens a file handle, writes the encoded JSON string, and explicitly calls sync() to ensure data is flushed to disk.',
      'url': '././~/FileSpec.prototype.writeJson.html',
      'category': 'Write Operations',
      'deprecated': false,
    }, {
      'id': 'namespace_filespec',
      'kind': [{ 'char': 'm', 'kind': 'Method', 'title': 'Method' }],
      'name': 'FileSpec.prototype.writeToml',
      'file': '.',
      'doc':
        'Writes data to the file in TOML format. This method uses a high-durability write strategy: it opens a file handle, writes the encoded TOML string, and explicitly calls sync() to ensure the data is flushed to the physical storage device before closing. The @std/toml dependency is loaded dynamically only when this method is called.',
      'url': '././~/FileSpec.prototype.writeToml.html',
      'category': 'Write Operations',
      'deprecated': false,
    }, {
      'id': 'namespace_filespec',
      'kind': [{ 'char': 'm', 'kind': 'Method', 'title': 'Method' }],
      'name': 'FileSpec.prototype.writeYaml',
      'file': '.',
      'doc':
        'Writes data to the file in YAML format. This method uses a high-durability write strategy: it opens a file handle, writes the encoded YAML string, and explicitly calls sync() to ensure the data is flushed to the physical storage device before closing. The @std/yaml dependency is loaded dynamically only when this method is called.',
      'url': '././~/FileSpec.prototype.writeYaml.html',
      'category': 'Write Operations',
      'deprecated': false,
    }, {
      'id': 'namespace_filespec',
      'kind': [{ 'char': 'm', 'kind': 'Method', 'title': 'Method' }],
      'name': 'FileSpec.prototype.ensureParentDir',
      'file': '.',
      'doc':
        'Ensures that the parent folder to this file exists.This method will consult our FolderSpec helpers and, if the parent folder does not exist, attempt to create it. Errors are thrown as specific subclasses of Error.FSError so callers can respond to common filesystem failure modes (e.g. not found, permission denied).',
      'url': '././~/FileSpec.prototype.ensureParentDir.html',
      'category': 'File Operations',
      'deprecated': false,
    }, {
      'id': 'namespace_filespec',
      'kind': [{ 'char': 'm', 'kind': 'Method', 'title': 'Method' }],
      'name': 'FileSpec.prototype.moveTo',
      'file': '.',
      'doc': 'Moves this file to a new location.',
      'url': '././~/FileSpec.prototype.moveTo.html',
      'category': 'File Operations',
      'deprecated': false,
    }, {
      'id': 'namespace_filespec',
      'kind': [{ 'char': 'm', 'kind': 'Method', 'title': 'Method' }],
      'name': 'FileSpec.prototype.safeCopy',
      'file': '.',
      'doc':
        'Safely copies the file to a new destination, with built-in handling for name conflicts to prevent accidental data loss.This method delegates to a shared safeCopy utility. If the destination file already exists, the default behavior is to back up the destination file by renaming it with a ~ suffix before performing the copy.',
      'url': '././~/FileSpec.prototype.safeCopy.html',
      'category': 'File Operations',
      'deprecated': false,
    }, {
      'id': 'namespace_filespec',
      'kind': [{ 'char': 'm', 'kind': 'Method', 'title': 'Method' }],
      'name': 'FileSpec.prototype.backup',
      'file': '.',
      'doc':
        'Backs up the current file by moving it to a new path, determined by the chosen strategy. This is useful for preserving a file before overwriting it. The moveTo operation is called with overwrite: true, ensuring the backup file is created.',
      'url': '././~/FileSpec.prototype.backup.html',
      'category': 'File Operations',
      'deprecated': false,
    }, {
      'id': 'namespace_filespec',
      'kind': [{ 'char': 'm', 'kind': 'Method', 'title': 'Method' }],
      'name': 'FileSpec.prototype.findAvailableIndexFilename',
      'file': '.',
      'doc':
        'Finds the next available indexed filename. For example, for filename.ext, tries filename-01.ext, filename-02.ext, etc until it finds a filename that is not used.',
      'url': '././~/FileSpec.prototype.findAvailableIndexFilename.html',
      'category': 'File Operations',
      'deprecated': false,
    }, {
      'id': 'namespace_filespec',
      'kind': [{ 'char': 'm', 'kind': 'Method', 'title': 'Method' }],
      'name': 'FileSpec.prototype.equalTo',
      'file': '.',
      'doc':
        'Compares this file to another file to determine if they are equal.The comparison is done first by size. If the sizes are equal, it can optionally perform a checksum comparison for byte-for-byte equality.',
      'url': '././~/FileSpec.prototype.equalTo.html',
      'category': 'Comparison',
      'deprecated': false,
    }, {
      'id': 'namespace_filespec',
      'kind': [{ 'char': 'm', 'kind': 'Method', 'title': 'Method' }],
      'name': 'FileSpec.prototype.chown',
      'file': '.',
      'doc': 'Changes the owner of the file.',
      'url': '././~/FileSpec.prototype.chown.html',
      'category': 'Permissions',
      'deprecated': false,
    }, {
      'id': 'namespace_filespec',
      'kind': [{ 'char': 'm', 'kind': 'Method', 'title': 'Method' }],
      'name': 'FileSpec.prototype.chgrp',
      'file': '.',
      'doc': 'Changes the group of the file.',
      'url': '././~/FileSpec.prototype.chgrp.html',
      'category': 'Permissions',
      'deprecated': false,
    }, {
      'id': 'namespace_filespec',
      'kind': [{ 'char': 'm', 'kind': 'Method', 'title': 'Method' }],
      'name': 'FileSpec.prototype.chmod',
      'file': '.',
      'doc': 'Changes the permissions of the file.',
      'url': '././~/FileSpec.prototype.chmod.html',
      'category': 'Permissions',
      'deprecated': false,
    }, {
      'id': 'namespace_filespec',
      'kind': [{ 'char': 'm', 'kind': 'Method', 'title': 'Method' }],
      'name': 'FileSpec.prototype.readableStream',
      'file': '.',
      'doc':
        'Creates a Web Streams API ReadableStream for reading from the file. This returns a modern web-compatible stream that works with fetch(), Response.body, and other Web APIs. Use this for modern JavaScript/TypeScript applications.',
      'url': '././~/FileSpec.prototype.readableStream.html',
      'category': 'Streams',
      'deprecated': false,
    }, {
      'id': 'namespace_filespec',
      'kind': [{ 'char': 'm', 'kind': 'Method', 'title': 'Method' }],
      'name': 'FileSpec.prototype.writableStream',
      'file': '.',
      'doc':
        'Creates a Web Streams API WritableStream for writing to the file. This returns a modern web-compatible stream that works with fetch(), Response.body, and other Web APIs. Use this for modern JavaScript/TypeScript applications.',
      'url': '././~/FileSpec.prototype.writableStream.html',
      'category': 'Streams',
      'deprecated': false,
    }, {
      'id': 'namespace_filespec',
      'kind': [{ 'char': 'm', 'kind': 'Method', 'title': 'Method' }],
      'name': 'FileSpec.prototype.nodeReadableStream',
      'file': '.',
      'doc':
        'Creates a Node.js readable stream for reading the file. This returns a Node.js stream compatible with libraries like PDFKit, Express, etc. Use this when working with Node.js libraries that expect Node.js streams.',
      'url': '././~/FileSpec.prototype.nodeReadableStream.html',
      'category': 'Streams',
      'deprecated': false,
    }, {
      'id': 'namespace_filespec',
      'kind': [{ 'char': 'm', 'kind': 'Method', 'title': 'Method' }],
      'name': 'FileSpec.prototype.nodeWritableStream',
      'file': '.',
      'doc':
        'Creates a Node.js writable stream for writing to the file. This returns a Node.js stream compatible with libraries like PDFKit, Express, etc. Use this when working with Node.js libraries that expect Node.js streams. PDFKit specifically requires this type of stream for proper PDF generation.',
      'url': '././~/FileSpec.prototype.nodeWritableStream.html',
      'category': 'Streams',
      'deprecated': false,
    }, {
      'id': 'namespace_filespec',
      'kind': [{ 'char': 'm', 'kind': 'Method', 'title': 'Method' }],
      'name': 'FileSpec.prototype.pipeFrom',
      'file': '.',
      'doc': '',
      'url': '././~/FileSpec.prototype.pipeFrom.html',
      'category': 'Streams',
      'deprecated': false,
    }, {
      'id': 'namespace_filespec',
      'kind': [{ 'char': 'm', 'kind': 'Method', 'title': 'Method' }],
      'name': 'FileSpec.prototype.pipeTo',
      'file': '.',
      'doc': '',
      'url': '././~/FileSpec.prototype.pipeTo.html',
      'category': 'Streams',
      'deprecated': false,
    }, {
      'id': 'namespace_filespec',
      'kind': [{ 'char': 'm', 'kind': 'Method', 'title': 'Method' }],
      'name': 'FileSpec.prototype.writer',
      'file': '.',
      'doc': '',
      'url': '././~/FileSpec.prototype.writer.html',
      'category': 'Streams',
      'deprecated': false,
    }, {
      'id': 'namespace_filespec',
      'kind': [{ 'char': 'm', 'kind': 'Method', 'title': 'Method' }],
      'name': 'FileSpec.prototype.digest',
      'file': '.',
      'doc': "Generates a digest (hash) of the file's contents using the specified algorithm.",
      'url': '././~/FileSpec.prototype.digest.html',
      'category': 'File Metadata',
      'deprecated': false,
    }, {
      'id': 'namespace_filespec',
      'kind': [{ 'char': 'm', 'kind': 'Method', 'title': 'Method' }],
      'name': 'FileSpec.prototype.checksum',
      'file': '.',
      'doc': 'For files, calculate the checksum of this file using SHA1',
      'url': '././~/FileSpec.prototype.checksum.html',
      'deprecated': true,
    }, {
      'id': 'namespace_filespec',
      'kind': [{ 'char': 'm', 'kind': 'Method', 'title': 'Method' }],
      'name': 'FileSpec.prototype.readJsonEx',
      'file': '.',
      'doc':
        'Reads the file as JSON, parses it, and performs a deep copy with optional transformations. If the file is JSONC, comments are stripped before parsing.This method is unique in that it allows you to deeply clone and transform JSON data as it is read from disk, supporting advanced options such as recursive file inclusion, RegExp detection, and custom transformation hooks.',
      'url': '././~/FileSpec.prototype.readJsonEx.html',
      'deprecated': true,
    }, {
      'id': 'namespace_filespec',
      'kind': [{ 'char': 'm', 'kind': 'Method', 'title': 'Method' }],
      'name': 'FileSpec.prototype.writeJsonEx',
      'file': '.',
      'doc': '',
      'url': '././~/FileSpec.prototype.writeJsonEx.html',
      'deprecated': true,
    }, {
      'id': 'namespace_filespec',
      'kind': [{ 'char': 'm', 'kind': 'Method', 'title': 'Method' }],
      'name': 'FileSpec.prototype.getUniquePath',
      'file': '.',
      'doc': 'Returns a temporary file path by appending a tilde (~).',
      'url': '././~/FileSpec.prototype.getUniquePath.html',
      'deprecated': true,
    }, {
      'id': 'namespace_filespec',
      'kind': [{ 'char': 'm', 'kind': 'Method', 'title': 'Method' }],
      'name': 'FileSpec.prototype.getUniqueFile',
      'file': '.',
      'doc': 'Returns a unique file path by appending a number if the file already exists.',
      'url': '././~/FileSpec.prototype.getUniqueFile.html',
      'deprecated': true,
    }],
  };
})();
